### ISSUE TITLE
示例程序小细节问题

### ISSUE THREAD

**Issue by HarrytheOrange** [rust-real-time-os/easy_lab#1]
uthread.h line 57 /// @param tcb 线程的控制块**q**

uthread.c line24 static inline void make_dumm**p**y_context(struct context *context) {

**Comment by HarrytheOrange** [comment]
uthread.h line49 函数功能与命名不明确
resume 恢复
/// @brief 挂起线程
/// @param 线程的控制块
void uthread_resume(struct uthread *tcb);

**Comment by SamuraiBUPT** [comment]
`uthread_resume` 就是把挂起的线程恢复运行状态。简而言之的说，就是利用`thread_switch`函数，把current_thread切换为参数传入的tcb。

有如下代码骨架：

```cpp
void uthread_resume(struct uthread* tcb) {
    thread_switch(&current_thread->context, &tcb->context);
}
```

**Comment by CheemsFries** [comment]
好的，已更正
