### ISSUE TITLE
关于Calling Convention的疑问

### ISSUE THREAD

**Issue by coffee3699** [rust-real-time-os/easy_lab#2]
### 对于caller-saved 和 callee-saved 的解释是不是有误？

我在[询问ChatGPT]([url](https://chat.openai.com/share/f2d27ae7-ec13-439c-8d17-e0c5c0cb4c50))的时候，GPT的认为此句话是错误的，并且从英语语法上来看**callee应该是被调者，caller是调用者**呀？

![image](https://github.com/rust-real-time-os/easy_lab/assets/42939049/474a2d40-eb8d-4bf8-bc9b-afd5a378ab5b)

是我的理解有误还是本身存在错误呢？

**Comment by CheemsFries** [comment]
确实，我更正一下
